# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/douglashirlinger/Documents/Max\ 8/Packages/max-sdk/source/basics/midiFilter/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/douglashirlinger/Documents/Max\ 8/Packages/max-sdk/source/max-sdk-base/script/max-posttarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/douglashirlinger/Documents/Max\ 8/Packages/max-sdk/source/max-sdk-base/script/max-pretarget.cmake))

/Users/douglashirlinger/Documents/Max\ 8/Packages/max-sdk/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/douglashirlinger/Documents/Max\ 8/Packages/max-sdk -B/Users/douglashirlinger/Documents/Max\ 8/Packages/max-sdk/build
